#!/usr/bin/env bash
# *************************************
#
#   Baseman MVCSS Starter
#   -> Creates an MVCSS starter application using drewbarontini/baseman
#
# -------------------------------------
#   Dependencies
# -------------------------------------
#
#  - bash-comment
#  - download-zip
#  - message
#
# -------------------------------------
#   Usage
# -------------------------------------
#
#  `baseman-mvcss-starter scratch` - creates a new project called 'scratch'
#
# *************************************

set -o errexit
set -o nounset
set -o pipefail

# -------------------------------------
#   Variables
# -------------------------------------

BASEMANURL='git@github.com:drewbarontini/baseman.git'

# -------------------------------------
#   Main
# -------------------------------------

bower install
echo
message green 'Bower is successfully set up!'

echo
bash-comment m 'Downloading MVCSS...'
echo
cd source/assets/stylesheets
download-zip 'https://github.com/mvcss/mvcss/archive/master.zip'
message green "Downloaded MVCSS!"
mv mvcss-master/application.sass application.sass
mv mvcss-master/foundation foundation
mv mvcss-master/components components
mv mvcss-master/structures structures
rm -rf mvcss-master

echo
bash-comment m 'Setting up a new Git repo...'
echo
cd ../../../
rm -rf .git
git init
git add .
git commit -m 'Initial commit'
echo
message green 'Set up new Git repo with initial commit!'

echo
bash-comment m 'Bundling...'
echo
gem install bundler
bundle install --binstubs

echo
bash-comment m 'Starting the Middleman server...'
echo
bundle exec middleman s
