#!/usr/bin/env bash
# *************************************
#
#   Spotify
#   -> Pulled from: https://github.com/hnarayanan/shpotify
#
# *************************************

running=`osascript -e 'application "Spotify" is running'`;

if [ $running == "true" ]; then

  state=`osascript -e 'tell application "Spotify" to player state as string'`;

  if [ $state = "playing" ]; then

    artist=`osascript -e 'tell application "Spotify" to artist of current track as string'`;
    track=`osascript -e 'tell application "Spotify" to name of current track as string'`;

    echo -e "$track - $artist";

  fi

fi
